version: '3.8'

services:
  db:
    image: postgres:15
    container_name: spbstu_db
    restart: always
    environment:
      POSTGRES_DB: SPBSTU_medical
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      timeout: 5s

  backend:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: SPBSTU_medical
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:8080"

volumes:
  pg_data:
 
